[package]
name = "ray"
version = "0.1.0"
authors = ["Thomas Pearson <tompearson2002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ray_math = { path = "../../lib/ray_math" }
rand = "0.8"
rayon = "1.5.0"
